### ISSUE TITLE
Padronizar README.md

### ISSUE THREAD

**Issue by bartier** [bartier/consulta-saldo-transurc#3]
O README.md desse repositório foi criado com base em um [template](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2). Atualmente está usando tanto inglês/português na descrição das informações.

Acredito que seria interessante padronizar para uma linguagem em si, como o código dos scripts estão em inglês, acredito que o ideal seria padronizar tudo para inglês.

**Comment by tuannyruiz** [comment]
Eu posso ajudar :)
Só uma pergunta, por que não padronizar em português já que é uma aplicação pra verificar o saldo do bilhete único de Campinas? 

De qualquer forma, se quiser pode atribuir a tarefa a mim que eu faço hoje mais tarde :)

**Comment by bartier** [comment]
@tuannyruiz Oi! Seu ponto é válido, pode ser que seja mais vantajoso ter o README.md em português.

Irei atribuir a você então! Agradecido =)

**Comment by tuannyruiz** [comment]
Oi, @bartier, eu finalizei essa tarefa, quando puder dá uma olhada :)
Valeu!

**Comment by bartier** [comment]
@tuannyruiz Assim que possível irei ver =)

**Comment by bartier** [comment]
#7 closes
