### ISSUE TITLE
Atribuir versão específica para Pipfile

### ISSUE THREAD

**Issue by bartier** [bartier/consulta-saldo-transurc#5]
Atualmente o Pipfile está com a definição para obter os pacotes na sua última versão:
![image](https://user-images.githubusercontent.com/18057391/67221366-b4625a80-f401-11e9-83a3-afe3bbbe74e0.png)

Caso exista uma alteração grande o suficiente entre versões das dependências, o script pode quebrar. Colocando versões específicas retiraria esse problema.

**Comment by JoseCarlosNF** [comment]
O projeto está utilizando as versões mais atuais e está sem problemas, certo? Posso fixar nas versões lançadas até a data da *inssue*.

**Comment by bartier** [comment]
@JoseCarlosNF Acredito que sim, porem como descrito na issue #6 nao estou conseguindo validar se esta tudo OK

Irei verificar hoje a noite se o site alterou alguma implementacao pra ter quebrado o script =/

**Comment by bartier** [comment]
Atualização: Como o projeto foi refatorado para usar selenium e corrigir o bug que impossibilitava a consulta do cartão o Pipfile e Pipfile.lock foram atualizados já, nesse sentido, irei fechar essa issue.
